version: '3.8'
services:
  postgres:
    image: postgres:15.2-alpine
    container_name: bookmark_database
    ports:
      - 5434:5432
    volumes:
      - postgres-db:/data/postgres
    env_file:
      - .env

  postgres_admin:
      image: dpage/pgadmin4:latest
      
      depends_on:
        - postgres
      
      env_file:
        - .env

      ports:
        - 5050:80

volumes:
  postgres-db:
    driver: local